# Generated by Django 4.1.2 on 2022-11-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kids_name', models.CharField(db_column='kids_name', max_length=128)),
                ('time_limit', models.IntegerField(db_column='time_limit')),
                ('parent_id', models.CharField(db_column='parent_id', max_length=320)),
                ('icon_image', models.CharField(db_column='icon_image', max_length=128)),
            ],
            options={
                'db_table': 'kids',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(db_column='user_name', max_length=128, unique=True)),
                ('password', models.CharField(db_column='password', max_length=256)),
                ('user_id', models.CharField(db_column='user_id', max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'parents',
            },
        ),
    ]
