# Form implementation generated from reading ui file 'famiowl_child_new.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FamiOwlChildNew(object):
    def setupUi(self, FamiOwlChildNew):
        FamiOwlChildNew.setObjectName("FamiOwlChildNew")
        FamiOwlChildNew.resize(900, 600)
        FamiOwlChildNew.setStyleSheet("QScrollBar:horizontal{\n"
"    height:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"border-radius:4px;\n"
"\n"
"}\n"
"QScrollBar::handle:horizontal{\n"
"    background:rgba(125,125,125,50%);\n"
"border-radius:4px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{\n"
"    background:rgba(125,125,125,100%);\n"
"    min-width:0;\n"
"}\n"
"QScrollBar::add-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:horizontal:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:horizontal,QScrollBar::sub-page:horizontal\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"\n"
"QScrollBar:vertical{\n"
"    width:8px;\n"
"    background:rgba(0,0,0,0%);\n"
"\n"
"}\n"
"QScrollBar::handle:vertical{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,50%);\n"
"    border-radius:4px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{\n"
"    width:0px;\n"
"    background:rgba(125,125,125,100%);\n"
"    border-radius:4px;\n"
"    min-width:20;\n"
"}\n"
"QScrollBar::add-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::sub-line:vertical:hover{\n"
"    height:0px;width:0px;\n"
"\n"
"}\n"
"QScrollBar::add-page:vertical,QScrollBar::sub-page:vertical\n"
"{\n"
"    background:rgba(0,0,0,10%);\n"
"    border-radius:4px;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(FamiOwlChildNew)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.central_frame = QtWidgets.QFrame(self.centralwidget)
        self.central_frame.setStyleSheet("QFrame#central_frame{\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius:20px;\n"
"}")
        self.central_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.central_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.central_frame.setObjectName("central_frame")
        self.central_frame_2 = QtWidgets.QFrame(self.central_frame)
        self.central_frame_2.setGeometry(QtCore.QRect(250, 40, 400, 500))
        self.central_frame_2.setStyleSheet("QFrame#central_frame_2{\n"
"    background-color: rgb(240, 240, 240);\n"
"    border-radius:20px;\n"
"}")
        self.central_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.central_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.central_frame_2.setObjectName("central_frame_2")
        self.profile_select_button = QtWidgets.QPushButton(self.central_frame_2)
        self.profile_select_button.setGeometry(QtCore.QRect(125, 90, 150, 150))
        self.profile_select_button.setStyleSheet("border-radius:32px;\n"
"border: none;\n"
"background: black;")
        self.profile_select_button.setText("")
        self.profile_select_button.setObjectName("profile_select_button")
        self.child_name_line = QtWidgets.QLineEdit(self.central_frame_2)
        self.child_name_line.setGeometry(QtCore.QRect(100, 280, 200, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.child_name_line.sizePolicy().hasHeightForWidth())
        self.child_name_line.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.child_name_line.setFont(font)
        self.child_name_line.setStyleSheet("")
        self.child_name_line.setText("")
        self.child_name_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.child_name_line.setObjectName("child_name_line")
        self.add_profile_button = QtWidgets.QPushButton(self.central_frame_2)
        self.add_profile_button.setGeometry(QtCore.QRect(100, 350, 200, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.add_profile_button.sizePolicy().hasHeightForWidth())
        self.add_profile_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.add_profile_button.setFont(font)
        self.add_profile_button.setStyleSheet("background-color: rgb(60, 32, 228);\n"
"color:rgb(255, 255, 255);\n"
"border-radius:20px;")
        self.add_profile_button.setObjectName("add_profile_button")
        self.horizontalLayout_8.addWidget(self.central_frame)
        FamiOwlChildNew.setCentralWidget(self.centralwidget)

        self.retranslateUi(FamiOwlChildNew)
        QtCore.QMetaObject.connectSlotsByName(FamiOwlChildNew)

    def retranslateUi(self, FamiOwlChildNew):
        _translate = QtCore.QCoreApplication.translate
        FamiOwlChildNew.setWindowTitle(_translate("FamiOwlChildNew", "FamiOwl Client"))
        self.child_name_line.setPlaceholderText(_translate("FamiOwlChildNew", "Name"))
        self.add_profile_button.setText(_translate("FamiOwlChildNew", "Add Profile"))
