# Form implementation generated from reading ui file 'signin_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QMovie


class Ui_Signin_Window(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 451)
        MainWindow.setStyleSheet("background-color: black;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_layout = QtWidgets.QHBoxLayout()
        self.title_layout.setObjectName("title_layout")
        spacerItem = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                           QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_layout.addItem(spacerItem)
        self.famiowl_title_label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.famiowl_title_label.sizePolicy().hasHeightForWidth())
        self.famiowl_title_label.setSizePolicy(sizePolicy)
        self.famiowl_title_label.setText("")
        self.famiowl_title_label.setPixmap(QtGui.QPixmap("src/resource/famiowl_title.png"))
        self.famiowl_title_label.setScaledContents(False)
        self.famiowl_title_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.famiowl_title_label.setObjectName("famiowl_title_label")
        self.title_layout.addWidget(self.famiowl_title_label)
        spacerItem1 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.title_layout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.title_layout)
        self.owl_gif_layout = QtWidgets.QVBoxLayout()
        self.owl_gif_layout.setObjectName("owl_gif_layout")
        self.owl_gif = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owl_gif.sizePolicy().hasHeightForWidth())
        self.owl_gif.setSizePolicy(sizePolicy)
        self.owl_gif.setMaximumSize(QtCore.QSize(16777215, 179))
        self.owl_gif.setText("")
        self.owl_gif_movie = QMovie("src/resource/owl_gif.gif")
        self.owl_gif.setMovie(self.owl_gif_movie)
        self.owl_gif_movie.start()
        # self.owl_gif.setPixmap(QtGui.QPixmap(":/owl_gif/owl_gif.gif"))
        # self.owl_gif.setObjectName("owl_gif")
        self.owl_gif_layout.addWidget(self.owl_gif)
        self.verticalLayout.addLayout(self.owl_gif_layout)
        self.signin_layout = QtWidgets.QGridLayout()
        self.signin_layout.setObjectName("signin_layout")
        self.signup_button = QtWidgets.QPushButton(self.centralwidget)
        self.signup_button.setStyleSheet("background-color: transparent;\n"
                                         "color: white;")
        self.signup_button.setObjectName("signup_button")
        self.signin_layout.addWidget(self.signup_button, 3, 2, 1, 1)
        self.forget_pwd_button = QtWidgets.QPushButton(self.centralwidget)
        self.forget_pwd_button.setStyleSheet("background-color: transparent;\n"
                                             "color: white;\n"
                                             "\n"
                                             "")
        self.forget_pwd_button.setObjectName("forget_pwd_button")
        self.signin_layout.addWidget(self.forget_pwd_button, 2, 2, 1, 1)
        self.user_input_layout = QtWidgets.QVBoxLayout()
        self.user_input_layout.setObjectName("user_input_layout")
        self.pwd_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pwd_line.sizePolicy().hasHeightForWidth())
        self.pwd_line.setSizePolicy(sizePolicy)
        self.pwd_line.setStyleSheet("background-color: white;\n"
                                    "color: black;")
        self.pwd_line.setText("")
        self.pwd_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.pwd_line.setObjectName("pwd_line")
        self.user_input_layout.addWidget(self.pwd_line)
        self.userid_line = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.userid_line.sizePolicy().hasHeightForWidth())
        self.userid_line.setSizePolicy(sizePolicy)
        self.userid_line.setStyleSheet("background-color: white;\n"
                                       "color: black;")
        self.userid_line.setText("")
        self.userid_line.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.userid_line.setObjectName("userid_line")
        self.user_input_layout.addWidget(self.userid_line)
        self.signin_layout.addLayout(self.user_input_layout, 1, 2, 1, 1)
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_button.sizePolicy().hasHeightForWidth())
        self.login_button.setSizePolicy(sizePolicy)
        self.login_button.setStyleSheet("background-color: transparent;")
        self.login_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("src/resource/login_icon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.login_button.setIcon(icon)
        self.login_button.setIconSize(QtCore.QSize(60, 60))
        self.login_button.setObjectName("login_button")
        self.signin_layout.addWidget(self.login_button, 1, 3, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.signin_layout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(160, 20, QtWidgets.QSizePolicy.Policy.Fixed,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.signin_layout.addItem(spacerItem3, 1, 4, 1, 1)
        self.verticalLayout.addLayout(self.signin_layout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.signup_button.setText(_translate("MainWindow", "Sign up ->"))
        self.forget_pwd_button.setText(_translate("MainWindow", "Forget your password?"))
        self.pwd_line.setPlaceholderText(_translate("MainWindow", "User ID"))
        self.userid_line.setPlaceholderText(_translate("MainWindow", "Password"))
